### ISSUE TITLE
Consider not annexing at least top level .json, .tsv. and .md files

### ISSUE THREAD

**Issue by yarikoptic** [pni-data/.github#3]
ATM top level datasets text files are also annexed, which e.g. forbids (ATM) and in general complicates extraction of metadata even at the overall dataset level by e.g. our http://registry.datalad.org/ since it would need first to get such files.

Someone I guess could have just used `datalad -c text2git` to generally commit text files into git, but with BIDS/neuroimaging datasets it might be a "miss" in case of large .json or .gii files.  So best strategy might be just to explicitly list top level files to be placed into git with e.g. smth like

```
/* annex.largefiles=(((mimeencoding=binary)and(largerthan=0))or(largerthan=100kb))
```
which should (I did only limited testing for this particular rule) place all top level small (under 100kb) textfiles under git.

But of cause may be you made such a choice consciously (e.g. not to leak possible sensitive metadata in top level files either) and then such recommendation would not apply.

**Comment by spisakt** [comment]
Great recommendation, thanks a lot! 
Related discussion: #2 and #1.
